create table tb_cliente (id int4 generated by default as identity, dn varchar(255), nome varchar(255), primary key (id));
create table tb_compras (id int4 generated by default as identity, data_compra date, total_compra float8, cliente_id int4, primary key (id));
alter table if exists tb_compras add constraint FKto1hl9btn8n1ssr1yglhog601 foreign key (cliente_id) references tb_cliente;
INSERT INTO tb_cliente(nome,dn) VALUES ('Maria','14/12/2000');
INSERT INTO tb_compras(cliente_id,total_compra,data_compra) VALUES (1,100.0,'2021-05-15');
